-- Database Schema DDL for inventory_service
-- This DDL is provided to the AI model to understand the table structures and relationships.

CREATE TABLE inventory_service.provinces (
    code INT PRIMARY KEY,
    name VARCHAR(255),
    division_type VARCHAR(255),
    codename VARCHAR(255),
    phone_code INT
);

CREATE TABLE inventory_service.wards (
    code INT PRIMARY KEY,
    name VARCHAR(255),
    division_type VARCHAR(255),
    codename VARCHAR(255),
    province_code INT REFERENCES inventory_service.provinces(code)
);

CREATE TABLE inventory_service.banks (
    id INT PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(255),
    bin VARCHAR(255),
    short_name VARCHAR(255),
    logo VARCHAR(255),
    transfer_supported INT,
    lookup_supported INT,
    support INT,
    is_transfer INT,
    swift_code VARCHAR(255)
);

CREATE TABLE inventory_service.events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_name VARCHAR(255),
    description TEXT,
    venue VARCHAR(255),
    address VARCHAR(255),
    ward_code INT REFERENCES inventory_service.wards(code),
    province_code INT REFERENCES inventory_service.provinces(code),
    is_cancelled BOOLEAN DEFAULT FALSE,
    event_type VARCHAR(255), -- values: 'ONLINE', 'OFFLINE', 'HYBRID'
    banner_image VARCHAR(255),
    thumbnail_image VARCHAR(255),
    introduction TEXT,
    seat_map_image VARCHAR(255),
    total_seats INT,
    organizer_id BIGINT,
    bank_info_id BIGINT,
    is_featured BOOLEAN,
    short_description VARCHAR(255),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(255),
    allow_multiple_ticket_types_per_order BOOLEAN DEFAULT FALSE,
    allow_discount_code BOOLEAN DEFAULT FALSE,
    allow_resale BOOLEAN DEFAULT FALSE,
    max_resale_price_percentage DECIMAL(5, 4),
    organizer_royalty_fee_percentage DECIMAL(5, 4),
    post_purchase_instruction TEXT,
    check_in_instruction TEXT,
    entry_gate_instruction TEXT,
    reconciliation_note TEXT,
    approval_status VARCHAR(255), -- values: 'DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED', 'CANCELLED'
    current_step BIGINT,
    category VARCHAR(255), -- values: 'LIVESTAGE', 'STAGE_ART', 'WORKSHOP', 'SPORTS', 'EXHIBITION'
    latitude DECIMAL,
    longitude DECIMAL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE inventory_service.showtimes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT REFERENCES inventory_service.events(id),
    start_datetime TIMESTAMP,
    end_datetime TIMESTAMP,
    venue VARCHAR(255),
    address VARCHAR(255),
    ward_code INT REFERENCES inventory_service.wards(code),
    province_code INT REFERENCES inventory_service.provinces(code),
    is_cancelled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE inventory_service.ticket_types (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_name VARCHAR(255),
    description VARCHAR(255),
    price DECIMAL(19, 2),
    quantity_total INT,
    quantity_sold INT DEFAULT 0,
    min_purchase INT,
    max_purchase INT,
    sale_start_date TIMESTAMP,
    sale_end_date TIMESTAMP,
    ticket_type_status VARCHAR(255), -- values: 'AVAILABLE', 'SOLD_OUT', 'STOPPED'
    showtime_id BIGINT REFERENCES inventory_service.showtimes(id),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE inventory_service.user_favorite_event (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    event_id BIGINT REFERENCES inventory_service.events(id),
    liked_at TIMESTAMP
);

CREATE TABLE inventory_service.reviews (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT REFERENCES inventory_service.events(id),
    user_id BIGINT,
    rating INT,
    comment TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE inventory_service.review_images (
    review_id BIGINT REFERENCES inventory_service.reviews(id),
    image_url VARCHAR(255)
);

CREATE TABLE inventory_service.showtime_checkers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    showtime_id BIGINT REFERENCES inventory_service.showtimes(id),
    checker_id BIGINT,
    status VARCHAR(255), -- values: 'PENDING', 'APPROVED', 'REJECTED'
    assigned_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE inventory_service.event_views (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT REFERENCES inventory_service.events(id),
    user_id BIGINT,
    created_at TIMESTAMP
);
